# Generated by Django 3.1.2 on 2021-01-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='main_tag',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='images',
            field=models.FileField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
