# Generated by Django 3.1.2 on 2021-01-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210111_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoimage',
            name='logo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='media.logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logoimage',
            name='image',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
